# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baicregisterinfo',
            old_name='name',
            new_name='register_name',
        ),
    ]
