# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160803_0311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaicMortgageInfo',
        ),
        migrations.DeleteModel(
            name='BaicRecordInfo',
        ),
        migrations.DeleteModel(
            name='BaicStockIfo',
        ),
        migrations.RenameField(
            model_name='baicregisterinfo',
            old_name='registration_authority',
            new_name='reg_authority',
        ),
    ]
